name: Generate Slides

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        pip install pandas
        pip install jinja2

    - name: Generate slides using Python
      run: python slides/generate_slides.py

    - name: Install Pandoc
      run: sudo apt-get install pandoc

    - name: Convert Markdown to HTML using reveal.js
      run: |
        pandoc slides/slides.md -t revealjs -s -o slides/slides.html -V revealjs-url=./reveal.js -V theme=black

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Generate slides"
        git push
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
